### PR TITLE
Fixed exceptions thrown on composer dumpautoload.

### PR DESCRIPTION
**Pull request by GroovyCarrot**
When dependencies are configured with non-existent paths, rather than
being ignored, `DirectoryIterator::__construct()` would throw an
UnexpectedValueException: failed to open dir, and cause the process to fail.

UnexpectedValueException's thrown by `Scanner::fromTree()` and `Scanner::fromFile()`
have been caught and ignored, ideally this information could be fed back
to the user as a warning, without the process failing. This would
require the Composer IO dependency injecting.

I was going to add a test, however ComposerImporter is somewhat difficult to unit test due to the logic in the constructor. An example of this to manually test however, is if you `hhvm composer.phar require symfony/symfony:^3.2`. Symfony has an obsolete entry in it's composer.json https://github.com/symfony/symfony/blob/master/composer.json#L115.
Technically this is an issue on Symfony's end, however this should not really break composer for the client, and composer itself just ignores this missing directory.

### CODE REVIEW

**Comment by fredemmott** [comment]
Thanks - sorry, I need you to fill out https://code.facebook.com/cla before I can look at this

**Comment by GroovyCarrot** [comment]
Sure, no problem

**Comment by GroovyCarrot** [comment]
@fredemmott have corrected to your code formatting standards

**Comment by fredemmott** [comment]
For future: It's good practice to make unused variables begin with `$_`; if there's only one and the context is clear, like it is here, that can be the entire variable - otherwise things like `$_e` are common. Not a blocker for this though.

**Pull request merged**
